network:
  version: 2
  ethernets:
    eth0:
      dhcp4: no
      dhcp6: no
      addresses:
        - 2001:6a8:2880:a020::5b/64
        - 193.191.176.91/24
      routes:
        - to: default
          via: 2001:6a8:2880:a020::fe
        - to: default
          via: 193.191.176.254
      nameservers:
        addresses:
          - 8.8.8.8
          - 2001:4860:4860::8888

