#!/bin/bash

ZONE_NAME=$1
NAME_SERVER="ns.$ZONE_NAME.vic-menten.sasm.uclllabs.be"
ZONE_FILE="/etc/bind/zones/$ZONE_NAME.vic-menten.sasm.uclllabs.be"
MASTER_ZONE_FILE="/etc/bind/zones/db.vic-menten.sasm.uclllabs.be"

if [ -z "$ZONE_NAME" ]; then
    echo "Error: Zone name parameter is missing"
    exit 1
fi

serial=$(grep -oP "^\s*[0-9]+\s+;\s+Serial" "$MASTER_ZONE_FILE" | awk '{print $1}')

if [ -z "$serial" ]; then
    echo "Error: Serial number not found in $MASTER_ZONE_FILE"
    exit 1
fi

new_serial=$((serial + 1))
if sed -i "s/^\(\s*\)$serial/\1$new_serial/" "$MASTER_ZONE_FILE"; then
    echo "Serial number updated in $MASTER_ZONE_FILE"
else
    echo "Error: Failed to update serial number in $MASTER_ZONE_FILE"
    exit 1
fi

cat << EOF > "$ZONE_FILE"
\$TTL 300
@       IN      SOA     ns.vic-menten.sasm.uclllabs.be. root.vic-menten.sasm.uclllabs.be. (
                        $new_serial    ; Serial
                        300            ; Refresh
                        300            ; Retry
                        60800          ; Expire
                        300     )      ; Negative Cache TTL
;

@       IN      NS      ns.vic-menten.sasm.uclllabs.be.
ns      IN      A       193.191.176.91
EOF

if [ $? -ne 0 ]; then
    echo "Failed to create zone file: $ZONE_FILE"
    exit 1
fi
echo "Zone file created at $ZONE_FILE"

echo "zone \"$ZONE_NAME.vic-menten.sasm.uclllabs.be\" {
        type master;
        notify yes;
        file \"/etc/bind/zones/$ZONE_NAME.vic-menten.sasm.uclllabs.be\";
};" >> /etc/bind/named.conf.yoda-zones

echo "$ZONE_NAME        IN      NS      ns.vic-menten.sasm.uclllabs.be.
ns.$ZONE_NAME   IN      A       193.191.176.91
" >> "$MASTER_ZONE_FILE"

if [ $? -ne 0 ]; then
    echo "Error: Failed to add NS record to $MASTER_ZONE_FILE"
    exit 1
else
    echo "NS record added to $MASTER_ZONE_FILE"
fi

systemctl restart bind9
if [ $? -eq 0 ]; then
    echo "Configuration applied and BIND service restarted"
else
    echo "Error: Failed to restart BIND service"
    exit 1
fi

